spring:
  application:
    name: personal-api
  datasource:
    url: jdbc:postgresql://localhost:5432/personaldb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
      
de013:
  app:
    jwtCookieName: de013
    jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9heyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQhSflKxwRJSMeKKF2QT4fwpMeJf36POk6yJVhadQssw5c
    jwtExpirationMs: 86400000

# LOGGING
# logging.level.org.springframework.web=DEBUG

# WEB CLIENT
web:
  admin:
    url: "http://localhost:4201"
  client:
    url: "http://localhost:4200"

file:
  upload-dir: D:\local_code\personal-web\images\
